export const CATALOG = {
  "Pantalla / Video": [
    "No da imagen / Pantalla negra",
    "Línea horizontal",
    "Línea vertical",
    "Mancha / Sombra en pantalla",
    "Parpadeo",
    "Distorsión de imagen",
    "Brillo irregular / No ajusta",
    "Píxeles dañados",
    "Imagen intermitente",
    "Estrellada / Quebrada",
    "Otra falla",
  ],
  "Batería / Carga": [
    "No carga",
    "Carga intermitente",
    "Se descarga rápidamente",
    "No detecta batería",
    "Se apaga al desconectar cargador",
    "Porcentaje de carga bloqueado",
    "Vida útil / Salud ≤ 65%",
    "Batería inflada",
    "Cargador no reconocido",
    "Otra falla",
  ],
  Teclado: [
    "Una tecla no funciona",
    "Varias teclas no funcionan",
    "Presiones falsas / Escribe solo",
    "Tecla pegada / Se repite",
    "Falla intermitente",
    "Teclado completo no responde",
    "Tecla dañada / Faltante",
    "Otra falla",
  ],
  "Touchpad / Mouse": [
    "No responde",
    "Falla intermitente",
    "Cursor se mueve solo",
    "Clic no responde",
    "Botones no funcionan",
    "Gestos no funcionan",
    "TrackPoint / PointStick",
    "Otra falla",
  ],
  "Encendido / Energía": [
    "No enciende",
    "Enciende y se apaga",
    "Apagado repentino",
    "Reinicio inesperado",
    "Solo encienden LEDs / Teclado",
    "Código de parpadeos",
    "Botón de encendido no responde",
    "Otra falla",
  ],
  "SSD / Almacenamiento": [
    "SSD no detectado",
    "No Boot Device",
    "Salud baja",
    "SMART / Sectores en riesgo",
    "Almacenamiento lento",
    "Error de lectura / escritura",
    "Capacidad incorrecta",
    "Otra falla",
  ],
  "Memoria RAM": [
    "RAM no detectada",
    "Error de memoria",
    "Capacidad incorrecta",
    "Falla de módulo",
    "Falla intermitente",
    "Otra falla",
  ],
  "Temperatura / Ventilación": [
    "Se calienta",
    "Sobrecalentamiento",
    "Ventilador ruidoso",
    "Ventilador no gira",
    "Ventilador siempre al máximo",
    "Apagado por temperatura",
    "Otra falla",
  ],
  "Sistema / Windows / Drivers": [
    "Pantalla azul / BSOD",
    "Se congela / Se pasma",
    "Windows no inicia",
    "Error de drivers",
    "Aplicaciones se cierran",
    "Sistema lento",
    "Falla después de actualización",
    "Error de recuperación",
    "Otra falla",
  ],
  "Puertos / USB / HDMI": [
    "USB no funciona",
    "HDMI sin señal",
    "USB-C no funciona",
    "Puerto de carga falla",
    "Jack de audio falla",
    "Ethernet no funciona",
    "Puerto flojo / Dañado",
    "Otra falla",
  ],
  Audio: [
    "Sin audio",
    "Audio distorsionado",
    "Volumen bajo",
    "Bocinas no funcionan",
    "Audífonos no detectados",
    "Audio intermitente",
    "Otra falla",
  ],
  "Cámara / Micrófono": [
    "Cámara no detectada",
    "Cámara con imagen negra",
    "Cámara intermitente",
    "Micrófono no detectado",
    "Micrófono con ruido",
    "Micrófono con volumen bajo",
    "Otra falla",
  ],
  "Wi-Fi / Bluetooth": [
    "Wi-Fi no aparece",
    "Wi-Fi no conecta",
    "Wi-Fi se desconecta",
    "Señal Wi-Fi débil",
    "Bluetooth no detecta dispositivos",
    "Bluetooth se desconecta",
    "Otra falla",
  ],
  "Carcasa / Bisagras / Estética": [
    "Rayones / Raspones",
    "Golpe / Abolladura",
    "Carcasa rota",
    "Separación de chasis",
    "Bisagra floja",
    "Bisagra rota",
    "Marco / Bezel dañado",
    "Otra falla",
  ],
  Periféricos: [
    "Cargador",
    "Dockstation",
    "Monitor externo",
    "Mouse externo",
    "Teclado externo",
    "Webcam",
    "Adaptador Wi-Fi",
    "Otro periférico",
  ],
  "BIOS / Firmware": [
    "No entra a BIOS",
    "Contraseña de BIOS",
    "Configuración UEFI",
    "Secure Boot",
    "BIOS corrupta",
    "Actualización fallida",
    "Error de Firmware",
    "Otra falla",
  ],
  Otro: ["Otra falla"],
};
export const REQUESTS = [
  "Diagnóstico general",
  "Validación de garantía",
  "Reparación",
  "Cambio de componente",
  "Dictamen técnico",
  "Pruebas de estrés",
];
